openapi: 3.1.0
servers:
  - url: /grpc
info:
  title: Trevstack API
  version: 0.0.1
  description: API for Trevstack
  contact:
    name: Trev
    email: spam@trev.xyz
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: []
