name: check

on:
  pull_request:
    branches: ['main']
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: https://github.com/actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: https://github.com/DeterminateSystems/nix-installer-action@90bb610b90bf290cad97484ba341453bd1cbefea # v19
      - uses: https://github.com/spotdemo4/nix-simple-cache-action@7c7ebfba2f6d07fa7b2fb1ba99769f7dfa04d6ac # v1.4.14

      - run: nix flake check -L --accept-flake-config
