name: check

on:
  pull_request:
    branches: ['main']
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: https://github.com/actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: https://github.com/DeterminateSystems/nix-installer-action@90bb610b90bf290cad97484ba341453bd1cbefea # v19
      - uses: https://github.com/spotdemo4/nix-simple-cache-action@e5a0f8762c433acdbac0014be557c66c310067ba # v1.2.0

      - run: nix flake check -L --accept-flake-config
