name: check

on:
  pull_request:
    branches: ['main']
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: https://github.com/actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: https://github.com/DeterminateSystems/nix-installer-action@90bb610b90bf290cad97484ba341453bd1cbefea # v19
      - uses: https://github.com/spotdemo4/nix-gitea-cache-action@9794e07ec3d1882dca19ed87b9a57c7fe56e2194 # v1.0.14

      - run: nix flake check -L --accept-flake-config
