name: flake

on:
  schedule:
    - cron: '5 4 * * *'
  workflow_dispatch:

jobs:
  flake:
    runs-on: ubuntu-latest
    steps:
      - uses: https://github.com/actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: https://github.com/DeterminateSystems/nix-installer-action@90bb610b90bf290cad97484ba341453bd1cbefea # v19
      - uses: https://github.com/spotdemo4/nix-simple-cache-action@76d4caada5afa7ad809b5f364e6d3aa15409be8e # v1.3.1

      - run: nix develop --accept-flake-config --command flake-checker -f
