name: update

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: https://github.com/actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: https://github.com/DeterminateSystems/nix-installer-action@90bb610b90bf290cad97484ba341453bd1cbefea # v19
      - uses: https://github.com/spotdemo4/nix-simple-cache-action@399c7ed4d18f9a2063f4d1c34f7508c359bf87d3 # v1.3.3

      - name: Renovate
        env:
          RENOVATE_CONFIG_FILE: .gitea/renovate-global.json
          RENOVATE_TOKEN: ${{ secrets.RENOVATE_TOKEN }}
          RENOVATE_GITHUB_COM_TOKEN: ${{ secrets.GH_TOKEN }}
        run: nix develop --accept-flake-config --command renovate
