name: vulnerable

on:
  schedule:
    - cron: '5 4 * * *'
  workflow_dispatch:

jobs:
  npm:
    runs-on: ubuntu-latest
    steps:
      - uses: https://github.com/actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: https://github.com/DeterminateSystems/nix-installer-action@90bb610b90bf290cad97484ba341453bd1cbefea # v19
      - uses: https://github.com/spotdemo4/nix-simple-cache-action@1af7a0acccff9f9a8b11934e4c355ed9dbd12e87 # v1.4.7

      - run: nix develop --accept-flake-config --command npm audit --audit-level moderate
