// @generated by protoc-gen-es v2.6.1 with parameter "target=ts"
// @generated from file user/v1/user.proto (package user.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "../../buf/validate/validate_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file user/v1/user.proto.
 */
export const file_user_v1_user: GenFile = /*@__PURE__*/
  fileDesc("ChJ1c2VyL3YxL3VzZXIucHJvdG8SB3VzZXIudjEiXAoEVXNlchIKCgJpZBgBIAEoBRIQCgh1c2VybmFtZRgCIAEoCRIfChJwcm9maWxlX3BpY3R1cmVfaWQYAyABKAVIAIgBAUIVChNfcHJvZmlsZV9waWN0dXJlX2lkIhAKDkdldFVzZXJSZXF1ZXN0Ii4KD0dldFVzZXJSZXNwb25zZRIbCgR1c2VyGAEgASgLMg0udXNlci52MS5Vc2VyIngKFVVwZGF0ZVBhc3N3b3JkUmVxdWVzdBIdCgxvbGRfcGFzc3dvcmQYASABKAlCB7pIBHICEAUSHQoMbmV3X3Bhc3N3b3JkGAIgASgJQge6SARyAhAFEiEKEGNvbmZpcm1fcGFzc3dvcmQYAyABKAlCB7pIBHICEAUiNQoWVXBkYXRlUGFzc3dvcmRSZXNwb25zZRIbCgR1c2VyGAEgASgLMg0udXNlci52MS5Vc2VyIj4KEEdldEFQSUtleVJlcXVlc3QSEAoIcGFzc3dvcmQYASABKAkSGAoQY29uZmlybV9wYXNzd29yZBgCIAEoCSIgChFHZXRBUElLZXlSZXNwb25zZRILCgNrZXkYASABKAkiPgobVXBkYXRlUHJvZmlsZVBpY3R1cmVSZXF1ZXN0EhEKCWZpbGVfbmFtZRgBIAEoCRIMCgRkYXRhGAIgASgMIjsKHFVwZGF0ZVByb2ZpbGVQaWN0dXJlUmVzcG9uc2USGwoEdXNlchgBIAEoCzINLnVzZXIudjEuVXNlciIhCh9CZWdpblBhc3NrZXlSZWdpc3RyYXRpb25SZXF1ZXN0IjgKIEJlZ2luUGFzc2tleVJlZ2lzdHJhdGlvblJlc3BvbnNlEhQKDG9wdGlvbnNfanNvbhgBIAEoCSI3CiBGaW5pc2hQYXNza2V5UmVnaXN0cmF0aW9uUmVxdWVzdBITCgthdHRlc3RhdGlvbhgBIAEoCSIjCiFGaW5pc2hQYXNza2V5UmVnaXN0cmF0aW9uUmVzcG9uc2UyuAQKC1VzZXJTZXJ2aWNlEj4KB0dldFVzZXISFy51c2VyLnYxLkdldFVzZXJSZXF1ZXN0GhgudXNlci52MS5HZXRVc2VyUmVzcG9uc2UiABJTCg5VcGRhdGVQYXNzd29yZBIeLnVzZXIudjEuVXBkYXRlUGFzc3dvcmRSZXF1ZXN0Gh8udXNlci52MS5VcGRhdGVQYXNzd29yZFJlc3BvbnNlIgASRAoJR2V0QVBJS2V5EhkudXNlci52MS5HZXRBUElLZXlSZXF1ZXN0GhoudXNlci52MS5HZXRBUElLZXlSZXNwb25zZSIAEmUKFFVwZGF0ZVByb2ZpbGVQaWN0dXJlEiQudXNlci52MS5VcGRhdGVQcm9maWxlUGljdHVyZVJlcXVlc3QaJS51c2VyLnYxLlVwZGF0ZVByb2ZpbGVQaWN0dXJlUmVzcG9uc2UiABJxChhCZWdpblBhc3NrZXlSZWdpc3RyYXRpb24SKC51c2VyLnYxLkJlZ2luUGFzc2tleVJlZ2lzdHJhdGlvblJlcXVlc3QaKS51c2VyLnYxLkJlZ2luUGFzc2tleVJlZ2lzdHJhdGlvblJlc3BvbnNlIgASdAoZRmluaXNoUGFzc2tleVJlZ2lzdHJhdGlvbhIpLnVzZXIudjEuRmluaXNoUGFzc2tleVJlZ2lzdHJhdGlvblJlcXVlc3QaKi51c2VyLnYxLkZpbmlzaFBhc3NrZXlSZWdpc3RyYXRpb25SZXNwb25zZSIAQlUKC2NvbS51c2VyLnYxQglVc2VyUHJvdG9QAaICA1VYWKoCB1VzZXIuVjHKAgdVc2VyXFYx4gITVXNlclxWMVxHUEJNZXRhZGF0YeoCCFVzZXI6OlYxYgZwcm90bzM", [file_buf_validate_validate]);

/**
 * @generated from message user.v1.User
 */
export type User = Message<"user.v1.User"> & {
  /**
   * @generated from field: int32 id = 1;
   */
  id: number;

  /**
   * @generated from field: string username = 2;
   */
  username: string;

  /**
   * @generated from field: optional int32 profile_picture_id = 3;
   */
  profilePictureId?: number;
};

/**
 * Describes the message user.v1.User.
 * Use `create(UserSchema)` to create a new message.
 */
export const UserSchema: GenMessage<User> = /*@__PURE__*/
  messageDesc(file_user_v1_user, 0);

/**
 * @generated from message user.v1.GetUserRequest
 */
export type GetUserRequest = Message<"user.v1.GetUserRequest"> & {
};

/**
 * Describes the message user.v1.GetUserRequest.
 * Use `create(GetUserRequestSchema)` to create a new message.
 */
export const GetUserRequestSchema: GenMessage<GetUserRequest> = /*@__PURE__*/
  messageDesc(file_user_v1_user, 1);

/**
 * @generated from message user.v1.GetUserResponse
 */
export type GetUserResponse = Message<"user.v1.GetUserResponse"> & {
  /**
   * @generated from field: user.v1.User user = 1;
   */
  user?: User;
};

/**
 * Describes the message user.v1.GetUserResponse.
 * Use `create(GetUserResponseSchema)` to create a new message.
 */
export const GetUserResponseSchema: GenMessage<GetUserResponse> = /*@__PURE__*/
  messageDesc(file_user_v1_user, 2);

/**
 * @generated from message user.v1.UpdatePasswordRequest
 */
export type UpdatePasswordRequest = Message<"user.v1.UpdatePasswordRequest"> & {
  /**
   * @generated from field: string old_password = 1;
   */
  oldPassword: string;

  /**
   * @generated from field: string new_password = 2;
   */
  newPassword: string;

  /**
   * @generated from field: string confirm_password = 3;
   */
  confirmPassword: string;
};

/**
 * Describes the message user.v1.UpdatePasswordRequest.
 * Use `create(UpdatePasswordRequestSchema)` to create a new message.
 */
export const UpdatePasswordRequestSchema: GenMessage<UpdatePasswordRequest> = /*@__PURE__*/
  messageDesc(file_user_v1_user, 3);

/**
 * @generated from message user.v1.UpdatePasswordResponse
 */
export type UpdatePasswordResponse = Message<"user.v1.UpdatePasswordResponse"> & {
  /**
   * @generated from field: user.v1.User user = 1;
   */
  user?: User;
};

/**
 * Describes the message user.v1.UpdatePasswordResponse.
 * Use `create(UpdatePasswordResponseSchema)` to create a new message.
 */
export const UpdatePasswordResponseSchema: GenMessage<UpdatePasswordResponse> = /*@__PURE__*/
  messageDesc(file_user_v1_user, 4);

/**
 * @generated from message user.v1.GetAPIKeyRequest
 */
export type GetAPIKeyRequest = Message<"user.v1.GetAPIKeyRequest"> & {
  /**
   * @generated from field: string password = 1;
   */
  password: string;

  /**
   * @generated from field: string confirm_password = 2;
   */
  confirmPassword: string;
};

/**
 * Describes the message user.v1.GetAPIKeyRequest.
 * Use `create(GetAPIKeyRequestSchema)` to create a new message.
 */
export const GetAPIKeyRequestSchema: GenMessage<GetAPIKeyRequest> = /*@__PURE__*/
  messageDesc(file_user_v1_user, 5);

/**
 * @generated from message user.v1.GetAPIKeyResponse
 */
export type GetAPIKeyResponse = Message<"user.v1.GetAPIKeyResponse"> & {
  /**
   * @generated from field: string key = 1;
   */
  key: string;
};

/**
 * Describes the message user.v1.GetAPIKeyResponse.
 * Use `create(GetAPIKeyResponseSchema)` to create a new message.
 */
export const GetAPIKeyResponseSchema: GenMessage<GetAPIKeyResponse> = /*@__PURE__*/
  messageDesc(file_user_v1_user, 6);

/**
 * @generated from message user.v1.UpdateProfilePictureRequest
 */
export type UpdateProfilePictureRequest = Message<"user.v1.UpdateProfilePictureRequest"> & {
  /**
   * @generated from field: string file_name = 1;
   */
  fileName: string;

  /**
   * @generated from field: bytes data = 2;
   */
  data: Uint8Array;
};

/**
 * Describes the message user.v1.UpdateProfilePictureRequest.
 * Use `create(UpdateProfilePictureRequestSchema)` to create a new message.
 */
export const UpdateProfilePictureRequestSchema: GenMessage<UpdateProfilePictureRequest> = /*@__PURE__*/
  messageDesc(file_user_v1_user, 7);

/**
 * @generated from message user.v1.UpdateProfilePictureResponse
 */
export type UpdateProfilePictureResponse = Message<"user.v1.UpdateProfilePictureResponse"> & {
  /**
   * @generated from field: user.v1.User user = 1;
   */
  user?: User;
};

/**
 * Describes the message user.v1.UpdateProfilePictureResponse.
 * Use `create(UpdateProfilePictureResponseSchema)` to create a new message.
 */
export const UpdateProfilePictureResponseSchema: GenMessage<UpdateProfilePictureResponse> = /*@__PURE__*/
  messageDesc(file_user_v1_user, 8);

/**
 * @generated from message user.v1.BeginPasskeyRegistrationRequest
 */
export type BeginPasskeyRegistrationRequest = Message<"user.v1.BeginPasskeyRegistrationRequest"> & {
};

/**
 * Describes the message user.v1.BeginPasskeyRegistrationRequest.
 * Use `create(BeginPasskeyRegistrationRequestSchema)` to create a new message.
 */
export const BeginPasskeyRegistrationRequestSchema: GenMessage<BeginPasskeyRegistrationRequest> = /*@__PURE__*/
  messageDesc(file_user_v1_user, 9);

/**
 * @generated from message user.v1.BeginPasskeyRegistrationResponse
 */
export type BeginPasskeyRegistrationResponse = Message<"user.v1.BeginPasskeyRegistrationResponse"> & {
  /**
   * @generated from field: string options_json = 1;
   */
  optionsJson: string;
};

/**
 * Describes the message user.v1.BeginPasskeyRegistrationResponse.
 * Use `create(BeginPasskeyRegistrationResponseSchema)` to create a new message.
 */
export const BeginPasskeyRegistrationResponseSchema: GenMessage<BeginPasskeyRegistrationResponse> = /*@__PURE__*/
  messageDesc(file_user_v1_user, 10);

/**
 * @generated from message user.v1.FinishPasskeyRegistrationRequest
 */
export type FinishPasskeyRegistrationRequest = Message<"user.v1.FinishPasskeyRegistrationRequest"> & {
  /**
   * @generated from field: string attestation = 1;
   */
  attestation: string;
};

/**
 * Describes the message user.v1.FinishPasskeyRegistrationRequest.
 * Use `create(FinishPasskeyRegistrationRequestSchema)` to create a new message.
 */
export const FinishPasskeyRegistrationRequestSchema: GenMessage<FinishPasskeyRegistrationRequest> = /*@__PURE__*/
  messageDesc(file_user_v1_user, 11);

/**
 * @generated from message user.v1.FinishPasskeyRegistrationResponse
 */
export type FinishPasskeyRegistrationResponse = Message<"user.v1.FinishPasskeyRegistrationResponse"> & {
};

/**
 * Describes the message user.v1.FinishPasskeyRegistrationResponse.
 * Use `create(FinishPasskeyRegistrationResponseSchema)` to create a new message.
 */
export const FinishPasskeyRegistrationResponseSchema: GenMessage<FinishPasskeyRegistrationResponse> = /*@__PURE__*/
  messageDesc(file_user_v1_user, 12);

/**
 * @generated from service user.v1.UserService
 */
export const UserService: GenService<{
  /**
   * @generated from rpc user.v1.UserService.GetUser
   */
  getUser: {
    methodKind: "unary";
    input: typeof GetUserRequestSchema;
    output: typeof GetUserResponseSchema;
  },
  /**
   * @generated from rpc user.v1.UserService.UpdatePassword
   */
  updatePassword: {
    methodKind: "unary";
    input: typeof UpdatePasswordRequestSchema;
    output: typeof UpdatePasswordResponseSchema;
  },
  /**
   * @generated from rpc user.v1.UserService.GetAPIKey
   */
  getAPIKey: {
    methodKind: "unary";
    input: typeof GetAPIKeyRequestSchema;
    output: typeof GetAPIKeyResponseSchema;
  },
  /**
   * @generated from rpc user.v1.UserService.UpdateProfilePicture
   */
  updateProfilePicture: {
    methodKind: "unary";
    input: typeof UpdateProfilePictureRequestSchema;
    output: typeof UpdateProfilePictureResponseSchema;
  },
  /**
   * @generated from rpc user.v1.UserService.BeginPasskeyRegistration
   */
  beginPasskeyRegistration: {
    methodKind: "unary";
    input: typeof BeginPasskeyRegistrationRequestSchema;
    output: typeof BeginPasskeyRegistrationResponseSchema;
  },
  /**
   * @generated from rpc user.v1.UserService.FinishPasskeyRegistration
   */
  finishPasskeyRegistration: {
    methodKind: "unary";
    input: typeof FinishPasskeyRegistrationRequestSchema;
    output: typeof FinishPasskeyRegistrationResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_user_v1_user, 0);

