#!/usr/bin/env bash

git fetch
git_root=$(git rev-parse --show-toplevel)
updated=false

echo "updating nix flake"
cd "${git_root}"
nix flake update
if ! git diff --exit-code flake.lock; then
    git add flake.lock
    git commit -m "build(nix): updated nix dependencies"
fi

echo "updating protobuf"
cd "${git_root}"
git submodule update --rebase --remote
if ! git diff --exit-code proto; then
    git add proto
    git commit -m "build(proto): updated protobuf"
    echo "you need to buf generate!"
fi

echo "updating npm"
cd "${git_root}"
npm update --save && npm i
if ! git diff --exit-code package.json package-lock.json; then
    git add package-lock.json
    git add package.json
    git commit -m "build(client): updated npm dependencies"
    updated=true
fi

if [ "${updated}" = true ]; then
    echo "updating nix hashes"
    cd "${git_root}"
    nix-update --flake --version=skip default
    git add flake.nix
    git commit -m "build(nix): updated nix hashes"
fi