name: flake

on:
  schedule:
    - cron: '5 4 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  flake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: DeterminateSystems/nix-installer-action@90bb610b90bf290cad97484ba341453bd1cbefea # v19
      - uses: spotdemo4/nix-simple-cache-action@e5a0f8762c433acdbac0014be557c66c310067ba # v1.2.0

      - run: nix develop --accept-flake-config --command flake-checker -f
