name: update

on:
  schedule:
    - cron: '0 0 * * *'
    - cron: '30 0 * * *'
  workflow_dispatch:

jobs:
  runner:
    runs-on: ubuntu-latest
    outputs:
      label: ${{ steps.runner.outputs.label }}
    steps:
      - uses: actions/create-github-app-token@v2
        id: token
        with:
          app-id: ${{ vars.CLIENT_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}

      - name: Get runner
        id: runner
        run: |
          runners=$(curl -s -H "Accept: application/vnd.github+json" -H "Authorization: token ${{ steps.token.outputs.token }}" "https://api.github.com/repos/${{ github.repository }}/actions/runners")
          available=$(echo "$runners" | jq '.runners[] | select(.status == "online" and .labels[] .name == "self-hosted")')
          if [ -n "$available" ]; then
            echo "label=self-hosted" >> $GITHUB_OUTPUT
          else
            echo "label=ubuntu-latest" >> $GITHUB_OUTPUT
          fi

  renovate:
    needs: runner
    runs-on: ${{ needs.runner.outputs.label }}
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: nicknovitski/nix-develop@v1
        with:
          arguments: '.#ci'

      - uses: actions/create-github-app-token@v2
        id: token
        with:
          app-id: ${{ vars.CLIENT_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}

      - name: Renovate
        env:
          RENOVATE_CONFIG_FILE: .github/renovate-global.json
          RENOVATE_TOKEN: ${{ steps.token.outputs.token }}
        run: renovate

  flake:
    needs: runner
    runs-on: ${{ needs.runner.outputs.label }}
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          reinstall: true
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - uses: actions/create-github-app-token@v2
        id: token
        with:
          app-id: ${{ vars.CLIENT_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}

      - run: nix flake update --accept-flake-config

      - uses: peter-evans/create-pull-request@v7
        id: pr
        with:
          token: ${{ steps.token.outputs.token }}
          sign-commits: true
          commit-message: 'chore(deps): update nix flake'
          title: 'chore(deps): update nix flake'

      - name: Enable automerge
        if: ${{ steps.pr.outputs.pull-request-number }}
        env:
          GH_TOKEN: ${{ steps.token.outputs.token }}
        run: >
          gh pr merge
          --squash
          --auto
          --subject "chore(deps): update nix flake"
          "${{ steps.pr.outputs.pull-request-number }}"
