name: update

on:
  schedule:
    - cron: '0/30 * * * *'
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - uses: nicknovitski/nix-develop@v1
        with:
          arguments: '.#ci'

      - uses: actions/create-github-app-token@v2
        id: token
        with:
          app-id: ${{ vars.CLIENT_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}

      - name: Renovate
        env:
          RENOVATE_CONFIG_FILE: .github/renovate-global.json
          RENOVATE_TOKEN: ${{ steps.token.outputs.token }}
        run: renovate

  flake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - run: nix flake update --accept-flake-config

      - uses: actions/create-github-app-token@v2
        id: token
        with:
          app-id: ${{ vars.CLIENT_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}

      - uses: peter-evans/create-pull-request@v7
        id: pr
        with:
          token: ${{ steps.token.outputs.token }}
          sign-commits: true
          commit-message: 'chore(deps): update nix flake'
          title: 'chore(deps): update nix flake'

      - name: Enable automerge
        if: ${{ steps.pr.outputs.pull-request-number }}
        env:
          GH_TOKEN: ${{ steps.token.outputs.token }}
        run: >
          gh pr merge
          --squash
          --auto
          --subject "chore(deps): update nix flake"
          "${{ steps.pr.outputs.pull-request-number }}"
